todoapp:
  namespace: todoapp

  serviceAccount: todoapp-sa

  port: 8080

  configs:
    PYTHONUNBUFFERED: "1"

  secrets:
    SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
    DB_NAME: app_db
    DB_USER: app_user
    DB_PASSWORD: "1234"
    DB_HOST: mysql-0.mysql-service.mysql.svc.cluster.local

  storage:
    size: 1Gi

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70

  resources:
    requests:
      memory: 256Mi
      cpu: 150m
    limits:
      memory: 256Mi
      cpu: 150m

prometheusOperator:
  admissionWebhooks:
    enabled: false
