apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.todoapp.namespace }}
data:
  {{- range $key, $value := .Values.todoapp.config }}
  {{ $key }}: {{ $value }}
  {{- end }}
