apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
  namespace: {{ .Values.todoapp.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.todoapp.port }}
    nodePort: 30007
