# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.mysql.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-app
  ports:
  - name: {{ .Values.mysql.service.portName }}
    port: {{ .Values.mysql.service.portNumber }}
  clusterIP: None

# pod-name.service-name.namespace.svc.cluster.local
# pod-name.service-name
# mysql-0.mysql-service.mysql.svc.cluster.local
